{% set version = "4.1" %}

package:
    name: opensim
    version: {{ version }}

source:
    git_url: https://github.com/opensim-org/opensim-core.git
    git_rev: {{ version }}
    git_depth: 1
    folder: opensim-core-source


build:
    number: 0
    run_exports:
        - {{ pin_subpackage('opensim', max_pin='x.x') }}
    detect_binary_files_with_prefix: true

requirements:
    build:
        # CMake 3.8 provides imported targets for OpenGL.
        - cmake >=3.8
        - ninja  # [win]
        - doxygen
        - swig 3.0.12
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - python
        - numpy
    host:
        - simbody >=3.7
        - spdlog >=1.4.1
        - ezc3d >=1.3.2
        - python
        - numpy
    run:
        - simbody >=3.7
        - spdlog >=1.4.1
        - ezc3d >=1.3.2
        - python
        - {{ pin_compatible('numpy') }}

test:
    imports:
        opensim

about:
    home: https://opensim.stanford.edu
    license: Apache-2.0
    license_file: LICENSE.txt
    dev_url: https://github.com/opensim-org
    doc_url: https://simtk-confluence.stanford.edu/display/OpenSim/OpenSim+Documentation
    summary: Modeling and simulation of musculoskeletal systems

extra:
    recipe-maintainers:
        - chrisdembia
        - kidzik

